# Made with love by Typo from TypoCreates (https://typocreates.com/#)
# Report bugs to me on Github <3.#


# Do you want to play a sound whenever you receive a message such as when you switch someone's gamemode?
# The sound effect will be played to anyone who receives a message. This is enabled by default.
# Options: true, false
do-sound-effects: true

# When changing another players gamemode, should the target player be notified when their gamemode is changed? This is enabled by default.
# Options: true, false
send-target-message: true

# Do you want to enable update checking? This is enabled by default.
# Options: true, false
update-checker: true

# All messages that are sent to the player, configurable here!
# {gamemode} will be replaced with the gamemode! (Only on applicable messages!)
# {player} will be replaced with the player! (Only on applicable messages!)
messages:
  target-gamemode-change: "Your gamemode has been set to {gamemode}."
  executor-confirmation: "{player}'s gamemode has been set to {gamemode}."
  executor-not-player: "You have to be a player or target a player to use this command."
  target-not-found: "That player could not be found, maybe they went offline?"
  too-many-args: "You can only have a maximum of 1 argument for this command."
  gamemode-locked: "Unable to change that users gamemode! Their gamemode is currently locked!"
  gamemode-blocked: "That user isn't allowed in {gamemode}!"

# Config version:
version: 1.0.2