name: Gamemodes
version: '1.2.0'
main: com.typocreates.gamemodes.Gamemodes
api-version: '1.20'
authors: [Typo]
description: Adds shortcuts and permissions for the /gamemode command.
website: https://typocreates.com/plugins/gamemodes/
commands:
  gma:
    description: Sets the targeted player to Adventure mode, the default player is the command executor.
    permission: gamemodes.gma
  gmc:
    description: Sets the targeted player to Creative mode, the default player is the command executor.
    permission: gamemodes.gmc
  gms:
    description: Sets the targeted player to Survival mode, the default player is the command executor.
    permission: gamemodes.gms
  gmsp:
    description: Sets the targeted player to Spectator mode, the default player is the command executor.
    permission: gamemodes.gmsp
  gmlock:
    description: Sets the targeted player to the selected gamemode and locks them in that gamemode until the /gmunlock command is used on them.
    permission: gamemodes.gmlock
  gmunlock:
    description: Allows the targeted player to switch gamemodes again after having the /gmlock command used on them.
    permission: gamemodes.gmunlock

permissions:
  gamemodes.all:
    description: Allows the player to use all the gamemode commands.
    children:
      gamemodes.gma: true
      gamemodes.gmc: true
      gamemodes.gms: true
      gamemodes.gmsp: true

  gamemodes.gma:
    description: Allows the player to use the /gma <player> command.

  gamemodes.gmc:
    description: Allows the player to use the /gmc <player> command.

  gamemodes.gms:
    description: Allows the player to use the /gms <player> command.

  gamemodes.gmsp:
    description: Allows the player to use the /gmsp <player> command.

  gamemodes.gmlock:
    description: Allows the player to use the /gmlock <player> <gamemode> command.

  gamemodes.gmunlock:
    description: Allows the player to use the /gmunlock <player> command.
