name: Gamemodes
version: '1.0.4'
main: com.typocreates.gamemodes.Gamemodes
api-version: '1.20'
authors: [Typo]
description: Adds shortcuts and permissions for the /gamemode command.
website: https://typocreates.com/plugins/gamemodes/
commands:
  gma:
    description: Sets the targeted player to Adventure mode, The default player is the command executor.
    permission: Gamemodes.GMA
    usage:
  gmc:
    description: Sets the targeted player to Creative mode, The default player is the command executor.
    permission: Gamemodes.GMC
    usage:
  gms:
    description: Sets the targeted player to Survival mode, The default player is the command executor.
    permission: Gamemodes.GMS
    usage:
  gmsp:
    description: Sets the targeted player to Spectator mode, The default player is the command executor.
    permission: Gamemodes.GMSP
    usage:
  gmlock:
    description: Sets the targeted player to the selected gamemode and locks them in that gamemode until the /GMUnlock command is used on them.
    permission: Gamemodes.GMLock
    usage:
  gmunlock:
    description: Allows the targeted player to switch gamemodes again after having the /GMLock command used on them.
    permission: Gamemodes.GMUnlock
    usage:

permissions:
  Gamemodes.ALL:
    description: Allows the player to use all the gamemode commands.
    children:
      Gamemodes.GMA: true
      Gamemodes.GMC: true
      Gamemodes.GMS: true
      Gamemodes.GMSP: true

  Gamemodes.GMA:
    description: Allows the player to use the /gma <player> command.

  Gamemodes.GMC:
    description: Allows the player to use the /gmc <player> command.

  Gamemodes.GMS:
    description: Allows the player to use the /gms <player> command.

  Gamemodes.GMSP:
    description: Allows the player to use the /gmsp <player> command.

  Gamemodes.GMLock:
    description: Allows the player to use the /GMLock <player> <gamemode> command.

  Gamemodes.GMUnlock:
    description: Allows the player to use the /GMUnlock <player> command.
