# Made with love by Typo from TypoCreates (https://typocreates.com/#)
# Report bugs to me on Discord or Spigot <3 (@TypoWasTaken).#


# Do you want to play a sound whenever you switch someone's gamemode?
# The sound effect will only be played for the person who ran the gamemode command. Default value = true
# Make sure to set this value to either true or false or the plugin might not work!
do-sound-effects: true